---
version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: blobscan
      POSTGRES_DB: blobscan_dev
    ports:
      - "25432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data


  web:
    image: blossomlabs/blobscan:stable
    command: web
    restart: always
    ports:
      - ${EXTERNAL_WEB_PORT}:3000
    env_file:
      - ".env"

  api:
    image: blossomlabs/blobscan:stable
    command: api
    restart: always
    ports:
      - ${EXTERNAL_API_PORT}:3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    env_file:
      - ".env"

  indexer:
    image: blossomlabs/blobscan-indexer:master
    network_mode: host
    restart: always
    env_file:
      - ".env"
    depends_on:
      api:
        condition: service_healthy
